### ISSUE TITLE
Crash in MeshWarper

### ISSUE THREAD

**Issue by akenmorris** [SCIInstitute/ShapeWorks#1460]
Crash in Mesh Warping, will add data as an automated test with fix:
```

    #0 0x110bc2210 in vtkAOSDataArrayTemplate<double>::GetTuple(long long, double*) vtkAOSDataArrayTemplate.txx:252
    #1 0x10768b2fb in shapeworks::MeshWarper::add_particle_vertices() MeshWarper.cpp:137
    #2 0x10768fa08 in shapeworks::MeshWarper::generate_warp() MeshWarper.cpp:338
    #3 0x10768869f in shapeworks::MeshWarper::check_warp_ready() MeshWarper.cpp:89
    #4 0x107687f32 in shapeworks::MeshWarper::build_mesh(Eigen::Matrix<double, -1, -1, 0, -1, -1> const&) MeshWarper.cpp:30
    #5 0x106b5f169 in shapeworks::MeshGenerator::build_mesh_from_points(vnl_vector<double> const&, int) MeshGenerator.cpp:85
    #6 0x106b5b6f1 in shapeworks::MeshGenerator::build_mesh(shapeworks::MeshWorkItem const&) MeshGenerator.cpp:45
    #7 0x106be4100 in shapeworks::MeshWorker::run() MeshWorker.cpp:23
    #8 0x11320b0dd in QThreadPoolThread::run()+0x6d (QtCore:x86_64+0x280dd)
    #9 0x11320e41e in QThreadPrivate::start(void*)+0x16e (QtCore:x86_64+0x2b41e)
    #10 0x7fff68fd8108 in _pthread_start+0x93 (libsystem_pthread.dylib:x86_64+0x6108)
    #11 0x7fff68fd3b8a in thread_start+0xe (libsystem_pthread.dylib:x86_64+0x1b8a)

```

**Comment by akenmorris** [comment]
Fixed in #1463
