### ISSUE TITLE
Windows builds all failing on GitHub Actions (documentation problem)

### ISSUE THREAD

**Issue by akenmorris** [SCIInstitute/ShapeWorks#1714]
From the logs:

```
2022-03-28T17:06:26.4146818Z + mkdocs build
2022-03-28T17:06:27.3675386Z Traceback (most recent call last):
2022-03-28T17:06:27.3676341Z   File "C:\Miniconda3\envs\shapeworks\lib\runpy.py", line 193, in _run_module_as_main
2022-03-28T17:06:27.3677193Z     "__main__", mod_spec)
2022-03-28T17:06:27.3677913Z   File "C:\Miniconda3\envs\shapeworks\lib\runpy.py", line 85, in _run_code
2022-03-28T17:06:27.3678893Z     exec(code, run_globals)
2022-03-28T17:06:27.3679607Z   File "C:\Miniconda3\envs\shapeworks\Scripts\mkdocs.exe\__main__.py", line 4, in <module>
2022-03-28T17:06:27.3680570Z   File "C:\Miniconda3\envs\shapeworks\lib\site-packages\mkdocs\__main__.py", line 16, in <module>
2022-03-28T17:06:27.3681433Z     from mkdocs import config                                 # noqa: E402
2022-03-28T17:06:27.3682365Z   File "C:\Miniconda3\envs\shapeworks\lib\site-packages\mkdocs\config\__init__.py", line 2, in <module>
2022-03-28T17:06:27.3683245Z     from mkdocs.config.defaults import DEFAULT_SCHEMA
2022-03-28T17:06:27.3684550Z   File "C:\Miniconda3\envs\shapeworks\lib\site-packages\mkdocs\config\defaults.py", line 1, in <module>
2022-03-28T17:06:27.3685746Z     from mkdocs.config import config_options
2022-03-28T17:06:27.3686787Z   File "C:\Miniconda3\envs\shapeworks\lib\site-packages\mkdocs\config\config_options.py", line 7, in <module>
2022-03-28T17:06:27.3687937Z     from mkdocs import utils, theme, plugins
2022-03-28T17:06:27.3688756Z   File "C:\Miniconda3\envs\shapeworks\lib\site-packages\mkdocs\theme.py", line 6, in <module>
2022-03-28T17:06:27.3689575Z     from mkdocs.utils import filters
2022-03-28T17:06:27.3690393Z   File "C:\Miniconda3\envs\shapeworks\lib\site-packages\mkdocs\utils\filters.py", line 11, in <module>
2022-03-28T17:06:27.3691259Z     @jinja2.contextfilter
2022-03-28T17:06:27.3691908Z AttributeError: module 'jinja2' has no attribute 'contextfilter'
```

@cchriste , might this be related to recent mkdocs changes?  Kind of confusing because I thought it was working before.

Possibly relevant:  

https://github.com/mkdocs/mkdocs/issues/2799

https://github.com/jimporter/mike/pull/95

https://github.com/mkdocs/mkdocs/pull/2800

**Comment by cchriste** [comment]
> @cchriste , might this be related to recent mkdocs changes? Kind of confusing because I thought it was working before.

Yes it might, and yes it was. Thanks for taking a shot at it. Fingers crossed.
