### ISSUE TITLE
Use cases are all broken and provide unhelpful error messages

### ISSUE THREAD

**Issue by akenmorris** [SCIInstitute/ShapeWorks#2020]
Something is probably wrong on the data portal, but if this were to happen in the future, we need to improve the error output.

Example:

```
Step 1. Extract Data
 _____    ___      .
|     |  /   \    / \
|  ShapeWorks Cloud  \
|_____|  \___/  /_____\

Login to ShapeWorks Data Portal successful

Total shape files found in Output/incremental_supershapes/: 0

Data available in Output/incremental_supershapes/  is sufficient, no new data will be downloaded
Done.


Step 2: Sort meshes into batches
Finding surface-to-surface distances for sorting...
Traceback (most recent call last):
  File "/home/amorris/sci/shapeworks/Examples/Python/RunUseCase.py", line 89, in <module>
    module.Run_Pipeline(args)
  File "/home/amorris/sci/shapeworks/Examples/Python/incremental_supershapes.py", line 105, in Run_Pipeline
    median_index = np.argmin(
  File "<__array_function__ internals>", line 180, in argmin
  File "/home/amorris/miniconda3/envs/shapeworks/lib/python3.9/site-packages/numpy/core/fromnumeric.py", line 1312, in argmin
    return _wrapfunc(a, 'argmin', axis=axis, out=out, **kwds)
  File "/home/amorris/miniconda3/envs/shapeworks/lib/python3.9/site-packages/numpy/core/fromnumeric.py", line 57, in _wrapfunc
    return bound(*args, **kwds)
ValueError: attempt to get argmin of an empty sequence
```

[verify.log](https://github.com/SCIInstitute/ShapeWorks/files/10995072/verify.log)

**Comment by zahidemon** [comment]
For some reason, most of the uploaded datasets are not [here](https://www.shapeworks-cloud.org/#/), probably the reason why the use cases are failing

**Comment by akenmorris** [comment]
Use cases are fixed and messages were improved
