### ISSUE TITLE
VerifyUseCases.py script problem

### ISSUE THREAD

**Issue by akenmorris** [SCIInstitute/ShapeWorks#2037]
```
Task exception was never retrieved
future: <Task finished name='Task-166' coro=<read_stream() done, defined at /Users/amorris/sci/releases/ShapeWorks-v6.4.0-rc3-mac/Examples/Python/VerifyUseCases.py:37> exception=ValueError('Separator is not found, and chunk exceed the limit')>
Traceback (most recent call last):
  File "/Users/amorris/miniconda3/envs/shapeworks/lib/python3.9/asyncio/streams.py", line 540, in readline
    line = await self.readuntil(sep)
  File "/Users/amorris/miniconda3/envs/shapeworks/lib/python3.9/asyncio/streams.py", line 618, in readuntil
    raise exceptions.LimitOverrunError(
asyncio.exceptions.LimitOverrunError: Separator is not found, and chunk exceed the limit

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/amorris/sci/releases/ShapeWorks-v6.4.0-rc3-mac/Examples/Python/VerifyUseCases.py", line 40, in read_stream
    line = await stream.readline()
  File "/Users/amorris/miniconda3/envs/shapeworks/lib/python3.9/asyncio/streams.py", line 549, in readline
    raise ValueError(e.args[0])
ValueError: Separator is not found, and chunk exceed the limit
```

My guess is that the new progress output has blown out the buffer on this stream output mechanism.

Apparently what we are doing is deprecated anyway:

```
VerifyUseCases.py:54: DeprecationWarning: The explicit passing of coroutine objects to asyncio.wait() is deprecated since Python 3.8, and scheduled for removal in Python 3.11.
  await asyncio.wait(
```

**Comment by akenmorris** [comment]
Resolved.
