### ISSUE TITLE
Conda's vtk package for windows is broken

### ISSUE THREAD

**Issue by akenmorris** [SCIInstitute/ShapeWorks#2108]
```
conda create --yes --name whatever python=3.9.13 'vtk=9.1.0=qt*' pip=22.1.2

python
import vtk
```

```
Python 3.9.13 (main, Oct 13 2022, 21:23:06) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import vkt
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'vkt'
>>> import vtk
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\amorris\miniconda3\envs\whatever\lib\site-packages\vtk.py", line 31, in <module>
    all_m = importlib.import_module('vtkmodules.all')
  File "C:\Users\amorris\miniconda3\envs\whatever\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\amorris\miniconda3\envs\whatever\lib\site-packages\vtkmodules\all.py", line 21, in <module>
    from .vtkViewsInfovis import *
ImportError: DLL load failed while importing vtkViewsInfovis: The specified module could not be found.
>>> exit()
```

**Comment by akenmorris** [comment]
We have worked around this.
