### ISSUE TITLE
Pybind Windows artifact issue with Jupyter Notebooks

### ISSUE THREAD

**Issue by iyerkrithika21** [SCIInstitute/ShapeWorks#867]
Artifact: [https://github.com/SCIInstitute/ShapeWorks/suites/1662040302/artifacts/30910217](url)
Kernels keep disconnecting when trying to run the notebooks.

To use:

1. Download and install the "Microsoft Visual C++ Redistributable for
Visual Studio 2015, 2017 and 2019." :

https://aka.ms/vs/16/release/vc_redist.x64.exe

2. Download and install Miniconda for Windows:

https://repo.anaconda.com/miniconda/Miniconda3-latest-Windows-x86_64.exe

3. Copy "C:\Program Files\ShapeWorks\Examples" to another location

4. Open "Anaconda Prompt"

5. CD to "C:\Program Files\ShapeWorks"

6. Run "conda_installs.bat"

7. CD to your copied Examples\Python\notebooks\tutorials location

8. Start the jupyter notebook by typing: `jupyter notebook`

9. Try to run the notebooks

**Comment by iyerkrithika21** [comment]
@akenmorris  @cchriste

**Comment by akenmorris** [comment]
I followed these instructions, and I get:
```

>jupyter notebook

'jupyter' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by akenmorris** [comment]
I'm just noticing that conda_installs.bat didn't work.  Tons of errors.

`/ Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\amorris\miniconda3\envs\shapeworks\lib\site-packages\notebook\nbextensions.py", line 206, in install_nbextension_python
    m, nbexts = _get_nbextension_metadata(module)
  File "C:\Users\amorris\miniconda3\envs\shapeworks\lib\site-packages\notebook\nbextensions.py", line 1117, in _get_nbextension_metadata
    m = import_item(module)
  File "C:\Users\amorris\miniconda3\envs\shapeworks\lib\site-packages\traitlets\utils\importstring.py", line 38, in import_item
    return __import__(parts[0])
  File "C:\Users\amorris\miniconda3\envs\shapeworks\lib\site-packages\latex_envs\__init__.py", line 3, in <module>
    from . import latex_envs
  File "C:\Users\amorris\miniconda3\envs\shapeworks\lib\site-packages\latex_envs\latex_envs.py", line 19, in <module>
    from IPython.display import HTML, display,JSON
  File "C:\Users\amorris\miniconda3\envs\shapeworks\lib\site-packages\IPython\__init__.py", line 49, in <module>
    from .terminal.embed import embed
  File "C:\Users\amorris\miniconda3\envs\shapeworks\lib\site-packages\IPython\terminal\embed.py", line 18, in <module>
    from IPython.terminal.interactiveshell import TerminalInteractiveShell
  File "C:\Users\amorris\miniconda3\envs\shapeworks\lib\site-packages\IPython\terminal\interactiveshell.py", line 16, in <module>
    from prompt_toolkit.document import Document
  File "C:\Users\amorris\miniconda3\envs\shapeworks\lib\site-packages\prompt_toolkit\__init__.py", line 16, in <module>
    from .interface import CommandLineInterface
  File "C:\Users\amorris\miniconda3\envs\shapeworks\lib\site-packages\prompt_toolkit\interface.py", line 19, in <module>
    from .application import Application, AbortAction
  File "C:\Users\amorris\miniconda3\envs\shapeworks\lib\site-packages\prompt_toolkit\application\__init__.py", line 1, in <module>
    from .application import Application
  File "C:\Users\amorris\miniconda3\envs\shapeworks\lib\site-packages\prompt_toolkit\application\application.py", line 41, in <module>
    from prompt_toolkit.buffer import Buffer
  File "C:\Users\amorris\miniconda3\envs\shapeworks\lib\site-packages\prompt_toolkit\buffer.py", line 9, in <module>
    from .completion import Completer, Completion, CompleteEvent
  File "C:\Users\amorris\miniconda3\envs\shapeworks\lib\site-packages\prompt_toolkit\completion\__init__.py", line 1, in <module>
    from .base import (
  File "C:\Users\amorris\miniconda3\envs\shapeworks\lib\site-packages\prompt_toolkit\completion\base.py", line 7, in <module>
    from prompt_toolkit.eventloop import generator_to_async_generator
ImportError: cannot import name 'generator_to_async_generator' from 'prompt_toolkit.eventloop' (C:\Users\amorris\miniconda3\envs\shapeworks\lib\site-packages\prompt_toolkit\eventloop\__init__.py)

\ Enabling: jupyter_nbextensions_configurator
- Writing config: C:\Users\amorris\miniconda3\envs\shapeworks\etc\jupyter
    - Validating...
      jupyter_nbextensions_configurator 0.4.1 ok
Enabling notebook nbextension nbextensions_configurator/config_menu/main...
Enabling tree nbextension nbextensions_configurator/tree_tab/main...

- Traceback (most recent call last):
  File "C:\Users\amorris\miniconda3\envs\shapeworks\Scripts\jupyter-contrib-nbextension-script.py", line 6, in <module>
    from jupyter_contrib_nbextensions.application import main
  File "C:\Users\amorris\miniconda3\envs\shapeworks\lib\site-packages\jupyter_contrib_nbextensions\application.py", line 15, in <module>
    from jupyter_contrib_nbextensions.install import (
  File "C:\Users\amorris\miniconda3\envs\shapeworks\lib\site-packages\jupyter_contrib_nbextensions\install.py", line 12, in <module>
    import latex_envs
ModuleNotFoundError: No module named 'latex_envs'

done
ERROR conda.core.link:_execute(698): An error occurred while installing package 'conda-forge::jupyter_latex_envs-1.4.6-py37hc8dfbb8_1001'.
Rolling back transaction: done

LinkError: post-link script failed for package conda-forge::jupyter_latex_envs-1.4.6-py37hc8dfbb8_1001
location of failed script: C:\Users\amorris\miniconda3\envs\shapeworks\Scripts\.jupyter_latex_envs-post-link.bat
==> script messages <==
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\amorris\miniconda3\envs\shapeworks\lib\site-packages\notebook\nbextensions.py", line 206, in install_nbextension_python
    m, nbexts = _get_nbextension_metadata(module)
  File "C:\Users\amorris\miniconda3\envs\shapeworks\lib\site-packages\notebook\nbextensions.py", line 1117, in _get_nbextension_metadata
    m = import_item(module)
  File "C:\Users\amorris\miniconda3\envs\shapeworks\lib\site-packages\traitlets\utils\importstring.py", line 38, in import_item
    return __import__(parts[0])
  File "C:\Users\amorris\miniconda3\envs\shapeworks\lib\site-packages\latex_envs\__init__.py", line 3, in <module>
    from . import latex_envs
  File "C:\Users\amorris\miniconda3\envs\shapeworks\lib\site-packages\latex_envs\latex_envs.py", line 19, in <module>
    from IPython.display import HTML, display,JSON
  File "C:\Users\amorris\miniconda3\envs\shapeworks\lib\site-packages\IPython\__init__.py", line 49, in <module>
    from .terminal.embed import embed
  File "C:\Users\amorris\miniconda3\envs\shapeworks\lib\site-packages\IPython\terminal\embed.py", line 18, in <module>
    from IPython.terminal.interactiveshell import TerminalInteractiveShell
  File "C:\Users\amorris\miniconda3\envs\shapeworks\lib\site-packages\IPython\terminal\interactiveshell.py", line 16, in <module>
    from prompt_toolkit.document import Document
  File "C:\Users\amorris\miniconda3\envs\shapeworks\lib\site-packages\prompt_toolkit\__init__.py", line 16, in <module>
    from .interface import CommandLineInterface
  File "C:\Users\amorris\miniconda3\envs\shapeworks\lib\site-packages\prompt_toolkit\interface.py", line 19, in <module>
    from .application import Application, AbortAction
  File "C:\Users\amorris\miniconda3\envs\shapeworks\lib\site-packages\prompt_toolkit\application\__init__.py", line 1, in <module>
    from .application import Application
  File "C:\Users\amorris\miniconda3\envs\shapeworks\lib\site-packages\prompt_toolkit\application\application.py", line 41, in <module>
    from prompt_toolkit.buffer import Buffer
  File "C:\Users\amorris\miniconda3\envs\shapeworks\lib\site-packages\prompt_toolkit\buffer.py", line 9, in <module>
    from .completion import Completer, Completion, CompleteEvent
  File "C:\Users\amorris\miniconda3\envs\shapeworks\lib\site-packages\prompt_toolkit\completion\__init__.py", line 1, in <module>
    from .base import (
  File "C:\Users\amorris\miniconda3\envs\shapeworks\lib\site-packages\prompt_toolkit\completion\base.py", line 7, in <module>
    from prompt_toolkit.eventloop import generator_to_async_generator
ImportError: cannot import name 'generator_to_async_generator' from 'prompt_toolkit.eventloop' (C:\Users\amorris\miniconda3\envs\shapeworks\lib\site-packages\prompt_toolkit\eventloop\__init__.py)

==> script output <==
stdout:
stderr:
return code: 1

()


(shapeworks) C:\Program Files\ShapeWorks>call jupyter contrib nbextension install --user
'jupyter' is not recognized as an internal or external command,
operable program or batch file.
`

**Comment by akenmorris** [comment]
I installed jupyter outside of conda_installs.bat

I ran it, but when the notebook tried to import shapeworks it failed:

`[I 18:06:42.263 NotebookApp] Kernel started: 9b140662-8116-4da4-a8a4-4c9dd68877e8, name: python3
[W 18:06:42.293 NotebookApp] 404 GET /nbextensions/widgets/notebook/js/extension.js?v=20201214180633 (::1) 22.07ms referer=http://localhost:8888/notebooks/api_demo.ipynb
Traceback (most recent call last):
  File "C:\Users\amorris\miniconda3\envs\shapeworks\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\amorris\miniconda3\envs\shapeworks\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\amorris\miniconda3\envs\shapeworks\lib\site-packages\ipykernel_launcher.py", line 15, in <module>
    from ipykernel import kernelapp as app
  File "C:\Users\amorris\miniconda3\envs\shapeworks\lib\site-packages\ipykernel\__init__.py", line 2, in <module>
    from .connect import *
  File "C:\Users\amorris\miniconda3\envs\shapeworks\lib\site-packages\ipykernel\connect.py", line 11, in <module>
    from IPython.core.profiledir import ProfileDir
  File "C:\Users\amorris\miniconda3\envs\shapeworks\lib\site-packages\IPython\__init__.py", line 49, in <module>
    from .terminal.embed import embed
  File "C:\Users\amorris\miniconda3\envs\shapeworks\lib\site-packages\IPython\terminal\embed.py", line 18, in <module>
    from IPython.terminal.interactiveshell import TerminalInteractiveShell
  File "C:\Users\amorris\miniconda3\envs\shapeworks\lib\site-packages\IPython\terminal\interactiveshell.py", line 16, in <module>
    from prompt_toolkit.document import Document
  File "C:\Users\amorris\miniconda3\envs\shapeworks\lib\site-packages\prompt_toolkit\__init__.py", line 16, in <module>
    from .interface import CommandLineInterface
  File "C:\Users\amorris\miniconda3\envs\shapeworks\lib\site-packages\prompt_toolkit\interface.py", line 19, in <module>
    from .application import Application, AbortAction
  File "C:\Users\amorris\miniconda3\envs\shapeworks\lib\site-packages\prompt_toolkit\application\__init__.py", line 1, in <module>
    from .application import Application
  File "C:\Users\amorris\miniconda3\envs\shapeworks\lib\site-packages\prompt_toolkit\application\application.py", line 41, in <module>
    from prompt_toolkit.buffer import Buffer
  File "C:\Users\amorris\miniconda3\envs\shapeworks\lib\site-packages\prompt_toolkit\buffer.py", line 9, in <module>
    from .completion import Completer, Completion, CompleteEvent
  File "C:\Users\amorris\miniconda3\envs\shapeworks\lib\site-packages\prompt_toolkit\completion\__init__.py", line 1, in <module>
    from .base import (
  File "C:\Users\amorris\miniconda3\envs\shapeworks\lib\site-packages\prompt_toolkit\completion\base.py", line 7, in <module>
    from prompt_toolkit.eventloop import generator_to_async_generator
ImportError: cannot import name 'generator_to_async_generator' from 'prompt_toolkit.eventloop' (C:\Users\amorris\miniconda3\envs\shapeworks\lib\site-packages\prompt_toolkit\eventloop\__init__.py)`

**Comment by iyerkrithika21** [comment]
The latest artifact after pybind merge worked fine
